config/routes.rb
Rails.application.routes.draw do
  resources :schedules do
    collection { post :import}
  end
  resources :specialties
  resources :specializations
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only =>[:show, :index]

  root 'pages#index'

  get 'schedule' => 'schedules#index'
  get '/users/sign_up' => 'registrations#new'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  require 'roo'



  def self.import(file)

    Schedule.destroy_all

    spreadsheet = open_spreadsheet(file)
    #raise spreadsheet.cell(2, 'E').inspect
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      schedule = find_by_id(row["id"]) || new
      #raise spreadsheet.row(i).inspect
      schedule.attributes = row.to_hash.slice(*row.to_hash.keys)
      #schedule.start_time = Time.at(schedule.start_time.days).local_time
      #schedule.end_time = Time.at(schedule.end_time.days).local_time
      schedule.save!
    end

  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
      when ".xls" then Roo::Excel.new(file.path, :ignore)
      when ".ods" then Roo::LibreOffice.new(file.path, packed: nil, file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end



end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  belongs_to :user
  belongs_to :specialty
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  has_many :specializations
  has_many :users, :through => :specializations
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :specializations
  has_many :specialties, :through => :specializations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

    @schedules = Schedule.all

    @potential_specialties = Specialty.all

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

 def sign_up_params
   params.require(:user).permit(:first, :last, :full_name, :email, :password, :password_confirmation)
 end

 def account_update_params
   params.require(:user).permit(:first, :last, :full_name, :email, :password, :password_confirmation, :current_password)
 end


end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Schedule.import(params[:file])
    redirect_to root_url, notice: "successfully uploaded!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:course_name, :class_name, :specialty, :start_date, :start_time, :end_date, :end_time, :location, :hours, :in_hst, :ct_assigned, :backup_ct)
    end
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController

  def create
    @user = User.find(params[:user])
    @specialization = @user.specializations.build(:specialty_id => params[:specialty_id])
    if @specialization.save
      flash[:notice] = "Added specialty"
      redirect_to request.referrer

    else
      flash[:notice] = "error"
      redirect_to request.referrer
    end
  end

  def destroy
    @user = User.find(params[:id])
    @specialization = @user.specializations.find_by_specialty_id(params[:specialty_id])

    if @specialization.destroy
      flash[:notice] = "Removed specialization."
      redirect_to request.referrer
    else
      flash[:error] = "Unable to remove specialization"
      redirect_to request.referrer
    end
  end


end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  before_action :set_specialty, only: [:show, :edit, :update, :destroy]

  # GET /specialties
  # GET /specialties.json
  def index
    @specialties = Specialty.all
  end

  # GET /specialties/1
  # GET /specialties/1.json
  def show
  end

  # GET /specialties/new
  def new
    @specialty = Specialty.new
  end

  # GET /specialties/1/edit
  def edit
  end

  # POST /specialties
  # POST /specialties.json
  def create
    @specialty = Specialty.new(specialty_params)

    respond_to do |format|
      if @specialty.save
        format.html { redirect_to @specialty, notice: 'Specialty was successfully created.' }
        format.json { render :show, status: :created, location: @specialty }
      else
        format.html { render :new }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialties/1
  # PATCH/PUT /specialties/1.json
  def update
    respond_to do |format|
      if @specialty.update(specialty_params)
        format.html { redirect_to @specialty, notice: 'Specialty was successfully updated.' }
        format.json { render :show, status: :ok, location: @specialty }
      else
        format.html { render :edit }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialties/1
  # DELETE /specialties/1.json
  def destroy
    @specialty.destroy
    respond_to do |format|
      format.html { redirect_to specialties_url, notice: 'Specialty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialty
      @specialty = Specialty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialty_params
      params.require(:specialty).permit(:specialty)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(:last)
  end

  def show
    @user = User.find(params[:id])
    @schedules = Schedule.all
    @potential_specialties = Specialty.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CTTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-default navbar-static-top">
    <div class="fluid-container">
      <div class="container">
        <div class="navbar-header">
          <button type="navbar-toggle" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand">cTTime</a>
        </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? && current_user.admin? %>
                <li><%= link_to "All Users", users_path %></li>
              <% end %>
              <% if user_signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <li><a href="/schedule">My schedule</a></li>
              <% else %>
                <li><%= link_to "Sign in", '/users/sign_in' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

<%= yield %>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</body>
</html>

app/views/pages/index.html.erb
<div class="page-header">

    <% if user_signed_in? %>

      <h1 class="col-sm-offset-1"><%= current_user.first %>, <small>see your schedule and find resources for further learning</small></h1>

    <% else %>
      <h1 class="col-sm-offset-1">Please, sign in to see your schedule!</h1>
    <% end %>

</div><!--header-->

<% if user_signed_in? %>

  <div class="container">

    <div class="col-sm-3" id="credentials">

      <h2>My Credentials</h1>

      <ul class="list-group">
        <% for specialty in current_user.specialties %>
          <li class="list-group-item"><%= specialty.specialty %></li>
        <% end %>
      </ul>

    </div><!--col-sm-4-->



    <div class="col-sm-5" id="quick_sched">

      <h2>Schedule at a glance</h1>

        <ul class="list-group">
          <% @schedules.each do |schedule| %>
            <% if (schedule.end_date >= Date.today) && (schedule.end_date <= Date.today + 7.days) %>


              <% if (schedule.ct_assigned.include? current_user.full_name) && (schedule.class_name == "PTO") %>

                <li class="list-group-item">
                  <h3>PTO</h3>
                  <p><%= schedule.start_date.strftime(("%A, %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_date.strftime(("%A, %m/%d/%y")) %> <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>                  <p><%= schedule.location %></p>
                </li>

              <% elsif schedule.ct_assigned.include? current_user.full_name %>

                <li class="list-group-item">
                  <h3><%= schedule.class_name %></h3>
                  <p><%= schedule.start_date.strftime(("%A %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>
                  <p><%= schedule.location %></p>
                </li>

              <% elsif schedule.backup_ct. == current_user.full_name %>

                <li class="list-group-item">
                  <h3>Thrive Support</h3>
                  <p><%= schedule.start_date.strftime(("%A %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>                  <p><%= schedule.location %></p>
                </li>

              <% end %>
            <% end %>
          <% end %>
        </ul>


    </div><!--col-sm-4-->



    <div class="col-sm-3" id="resources">

      <h2>Resources</h1>

    </div><!--col-sm-4-->

  </div><!--container-->

<% end %>

app/views/schedules/_form.html.erb
<% if current_user.admin? %>
  <div class="container" id="importBox">

    <div class="row">
      <h1>Import the schedule</h1>
    </div><!--row-->

    <div class="row">
      <%= form_tag import_schedules_path, multipart: true do %>
        <label for="file">File to Upload</label> <%= file_field_tag :file %>
        <%= submit_tag("Import", :id=>"submit")%>

    </div><!--row-->

  </div><!--container-->
  <% end %>

<% else %>

  <h3>This is restricted to administrators.</h3>


<% end %>
<br/>
<br/>
<br/>
<div class="container" id="loader">
</div>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>



<div class="container">
  <div class="scheduleList">
    <div class="row">

      <!-- the unordered list of classes for each user -->
      <% if user_signed_in? %>
      <div class="col-sm-10 col-sm-offset-1">
        <ul>
          <% @schedules.each do |schedule| %>
            <% if schedule.end_date >= Date.today %>


              <% if (schedule.ct_assigned.include? current_user.full_name) && (schedule.class_name == "PTO") %>

                <li class="list-group-item">
                  <h3>PTO</h3>
                  <p><%= schedule.start_date.strftime(("%A, %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_date.strftime(("%A, %m/%d/%y")) %> <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>                  <p><%= schedule.location %></p>
                </li>

              <% elsif schedule.ct_assigned.include? current_user.full_name %>

                <li class="list-group-item">
                  <h3><%= schedule.class_name %></h3>
                  <p><%= schedule.start_date.strftime(("%A %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>
                  <p><%= schedule.location %></p>
                </li>

              <% elsif schedule.backup_ct. == current_user.full_name %>

                <li class="list-group-item">
                  <h3>Thrive Support</h3>
                  <p><%= schedule.start_date.strftime(("%A %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>                  <p><%= schedule.location %></p>
                </li>

              <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>

      <% else %>

        <h2>You'll have to log in to view your schedule!</h2>

      <% end %>
    </div>
  </div>
</div>


<br>

app/views/schedules/new.html.erb
<%= render 'form' %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course name:</strong>
  <%= @schedule.course_name %>
</p>

<p>
  <strong>Class name:</strong>
  <%= @schedule.class_name %>
</p>

<p>
  <strong>Specialty:</strong>
  <%= @schedule.specialty %>
</p>

<p>
  <strong>Start:</strong>
  <%= @schedule.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @schedule.ending %>
</p>

<p>
  <strong>Location:</strong>
  <%= @schedule.location %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @schedule.hours %>
</p>

<p>
  <strong>In hst:</strong>
  <%= @schedule.in_hst %>
</p>

<p>
  <strong>Ct assigned:</strong>
  <%= @schedule.ct_assigned %>
</p>

<p>
  <strong>Backup ct:</strong>
  <%= @schedule.backup_ct %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/specialties/_form.html.erb
<%= form_for(@specialty) do |f| %>
  <% if @specialty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialty.errors.count, "error") %> prohibited this specialty from being saved:</h2>

      <ul>
      <% @specialty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :specialty %><br>
    <%= f.text_field :specialty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specialties/edit.html.erb
<h1>Editing Specialty</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialty %> |
<%= link_to 'Back', specialties_path %>

app/views/specialties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Specialties</h1>

<table>
  <thead>
    <tr>
      <th>Specialty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialties.each do |specialty| %>
      <tr>
        <td><%= specialty.specialty %></td>
        <td><%= link_to 'Show', specialty %></td>
        <td><%= link_to 'Edit', edit_specialty_path(specialty) %></td>
        <td><%= link_to 'Destroy', specialty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specialty', new_specialty_path %>

app/views/specialties/new.html.erb
<h1>New Specialty</h1>

<%= render 'form' %>

<%= link_to 'Back', specialties_path %>

app/views/specialties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specialty:</strong>
  <%= @specialty.specialty %>
</p>

<%= link_to 'Edit', edit_specialty_path(@specialty) %> |
<%= link_to 'Back', specialties_path %>

app/views/users/index.html.erb
<% if user_signed_in? && current_user.admin? %>
<div class="row text-center">
  <div class="col-sm-4 col-sm-offset-4">
    <ul class="list-group">
      <% @users.each do |user| %>
        <li class="list-group-item">
          <%= link_to user.full_name, user %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% else %>
  <h1>Sorry! You are not logged in as an admin</h1>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? && current_user.admin? %>
  <div class="page-header">

        <h1 class="col-sm-offset-1"><%= @user.full_name %>'s page</h1>

  </div><!--header-->



    <div class="container">

      <div class="col-sm-4" id="credentials">

        <h2>Credentials</h1>

          <ul class="list-group">
            <% for specialty in @user.specialties %>
              <li class="list-group-item clearfix">
                <%= specialty.specialty %>
                <span class="pull-right">
                  <div class="btn btn-xs">
                    <%= link_to '<span class="glyphicon glyphicon-minus red"></span>'.html_safe, specialization_path(:specialty_id => specialty, :user => @user), :method => :delete %>
                  </div>
                </span>
              </li>
            <% end %>
          </ul>

          <div id="add_specialty">
            <h2>Add a specialty <span class="pull-right"><div class="btn" id="show_list"><span class="glyphicon glyphicon-arrow-down green" id="arrow"</span></div></span></h2>
              <ul class="list-group" id="potential_specialty_list">
                <% @potential_specialties.each do |potential_specialty| %>
                  <% if !@user.specializations.exists?(:specialty => potential_specialty) %>

                    <li class="list-group-item clearfix"><%= potential_specialty.specialty %> <span class="pull-right"><div class="btn btn-xs"><%= link_to '<span class="glyphicon glyphicon-plus"></span>'.html_safe, specializations_path(:specialty_id => potential_specialty, :user => @user), :method => :post %></div></span></li>

                  <% end %>
                <% end %>
              </ul>

          </div>



      </div><!--col-sm-4-->



      <div class="col-sm-7" id="quick_sched">

        <h2><%= @user.first %>'s schedule</h1>

          <ul class="list-group">
            <% @schedules.each do |schedule| %>
              <% if (schedule.end_date >= Date.today)  %>


                <% if (schedule.ct_assigned.include? @user.full_name) && (schedule.class_name == "PTO") %>

                  <li class="list-group-item">
                    <h3>PTO</h3>
                    <p><%= schedule.start_date.strftime(("%A, %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_date.strftime(("%A, %m/%d/%y")) %> <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>                  <p><%= schedule.location %></p>
                  </li>

                <% elsif schedule.ct_assigned.include? @user.full_name %>

                  <li class="list-group-item">
                    <h3><%= schedule.class_name %></h3>
                    <p><%= schedule.start_date.strftime(("%A %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>
                    <p><%= schedule.location %></p>
                  </li>

                <% elsif schedule.backup_ct. == @user.full_name %>

                  <li class="list-group-item">
                    <h3>Thrive Support</h3>
                    <p><%= schedule.start_date.strftime(("%A %m/%d/%y")) %> <%= schedule.start_time.strftime(("%I:%M %p")) %> - <%= schedule.end_time.strftime(("%I:%M %p")) %> </p>                  <p><%= schedule.location %></p>
                  </li>

                <% end %>
              <% end %>
            <% end %>
          </ul>

      </div><!--col-sm-4-->







<% end %>